### ISSUE TITLE
new version of simulation notebook?

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift-examples#11]
The latest version of OceanParcels generate zarr files/store/archives. @philippemiron do you think your example notebook `simulation-data.ipynb` would work the same if it was loading a zarr file instead of a netcdf? I would think so ...

**Comment by philippemiron** [comment]
Yes, it doesn't change much. You only have to:

- (of course) switch the filename from `.nc` to `.zarr`
- and they also change the name of one dimension from `traj` to `trajectory`

**Comment by philippemiron** [comment]
Also, I realized that it was crashing due to the lack of memory in Binder. 

I think it would be simpler to redo with a new `.zarr` output from Parcels, but I don't have anything else publicly available somewhere to refer to...

**Comment by selipot** [comment]
That's where I should be able to come in in a few months ... stay tuned.

**Comment by philippemiron** [comment]
In the meantime, we could also simply reproduce this [example](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_output.ipynb) and used the Output.zarr that it generates. I just did it on my computer and it's only ~2MB so we could put the archive directly along with the example Notebooks.
