### ISSUE TITLE
Ordering trajectories of the GDP inside the ragged array by `deployment_date`

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift-examples#15]
There is an `order_by_enddate()` function ([here](https://github.com/Cloud-Drift/clouddrift/pull/25/files)) that could be easily added to the `gdp.py` and `gdp6h.py` modules. But before being able to add this, some cleaning has to be done upstream. More precisely:

- ID 2529260
  - https://www.aoml.noaa.gov/ftp/pub/phod/buoydata/dirfl_10001_15000.dat
  - https://www.aoml.noaa.gov/ftp/pub/phod/lumpkin/netcdf/buoydata_10001_15000/drifter_2529260.nc

- The deployment dates match
  - 2007/10/23 16:59
  - 2007-10-23T00:00

- End dates do not:
  - Directory file 2008/11/14 21:00
  - netCDF archive is 2009-03-12T00:00

**Comment by selipot** [comment]
Ok, this is all listed in the GDP issues google doc! Will bug the DAC about this again

**Comment by selipot** [comment]
Please see the email by Shaun Dolk. I think that should fix the issue once the `dirfl_10001_15000.dat` file is recreated. Does this satisfy you @philippemiron?

**Comment by philippemiron** [comment]
Yes. Once this is done, I can implement this.

**Comment by philippemiron** [comment]
I looked at this today and found out that some drifters' `deploy_date` is `nan` in the individual netCDF files (6-hourly and the hourly datasets). However, all drifters have a deployment time in the *dirfl* metadata files, so I think this should be reported to the GDP.

**Comment by selipot** [comment]
Ok will email the DAC. In the meantime can we do
``
if end_date == NaN do  end_date = time[0]
``
?

**Comment by philippemiron** [comment]
Yes, we could replace the `deploy_date` with the first time in the case that it's `nan`. But looking more into it, there are quite a lot of differences between the `Deployment_time` in the dirfl files, and the individual netCDFs... So even if I ordered with the data from the dirfl files, I can some unordered `deploy_time` in the ragged array.

**Comment by selipot** [comment]
@philippemiron is the `order_by_date` function depending on the `deploy_date` in the NetCDF files or from the `dirlf` files? In the first case the `order_by_date` will work even if the NetCDF files have missing values?

**Comment by philippemiron** [comment]
It's based on the dirlf files. I can order the trajectories, but then if you look at the `deploy_date` in the generated ragged arrays there are not in order. Because of differences I pointed out in the previous comments.

**Comment by selipot** [comment]
They are not in order in the ragged array files because some deploy_date are Nan but they *are* effectively in order according to the dirlf files? If not, then I do not understand.

**Comment by philippemiron** [comment]
As I said in the previous message, there are also mismatched between the dirfl values and the netCDF values. For example, if generate the ragged array with:
```
drifter_ids = gdp.download(n_random_id=100)
```
with the `order_by_date()` function added, I get the following `deploy_date` in the ragged array (without considering the nan).

```
plt.plot(ds.deploy_date[np.isfinite(ds.deploy_date)])
```
<img width="551" alt="Screenshot 2022-12-19 at 15 52 52" src="https://user-images.githubusercontent.com/387624/208499056-8b1b6fb0-f84e-465b-a2cf-06ceca7f1a8c.png">

In this case, one value is obviously out of order. So I look at the dirfl values:
- ID 43868
- Deployment date: 2014-11-01 03:11:00

Then look at the netCDF from the hourly dataset:
```
xr.open_dataset(f'../data/raw/gdp-v2.00/drifter_43868.nc').deploy_date.values
array(['**2010-10-02**T00:00:00.000000000'], dtype='datetime64[ns]')
```
and the time array from the same trajectory:
```
xr.open_dataset(f'../data/raw/gdp-v2.00/drifter_43868.nc').time.values
array([['2014-11-01T04:00:00.000000000', '2014-11-01T05:00:00.000000000',
        '2014-11-01T06:00:00.000000000', ...,
        '2015-04-30T19:00:00.000000000', '2015-04-30T20:00:00.000000000',
        '2015-04-30T21:00:00.000000000']], dtype='datetime64[ns]')
```
I don't know how this can happened, but it is 4 years off.. ?

**Comment by selipot** [comment]
I am very sorry @philippemiron, I skipped that [previous message](https://github.com/Cloud-Drift/clouddrift-examples/issues/15#issuecomment-1356655316). Ok, I get it, will report to the DAC.

**Comment by shaundolk** [comment]
@philippemiron @selipot buoy 43868 is indeed an odd one. After checking the database, it appears this buoy was indeed deployed on 10/02/2010, but the activation magnet was not removed, thus the buoy did not transmit. Somehow, the threaded activation magnet was dislodged some 4 years later and the buoy began transmitting data on 10/28/2014. For whatever reason, the first ~4 days of data were removed from the kriging process and the official dirfl start date was entered as 11/1.13/2014.

**Comment by shaundolk** [comment]
@philippemiron @selipot As buoy 43868 illustrates, discrepancies between dirfl start date and the deployment date listed (based on the date the buoy hits the water), are plentiful. While deployment date is helpful for diagnosing delayed activations and issues with individual sensors, I don't believe it should be listed as the deployment date. instead, I think the dirfl start date should be, as these start dates are QC'd and they're more relevant to data flow and the true beginning of drifter lifetimes. thoughts?

**Comment by selipot** [comment]
Thank you @shaundolk for this explanation, this makes sense to me now. What about if the NetCDF files created by the DAC were to include both the `deploy_[dat,lat,lon]` and `start_[date,lat,lon]` fields? Proper comment attributes should also be inlcuded with these variables to explain their meaning. I think both types of fields are useful for many scientific and logistic applications.

**Comment by philippemiron** [comment]
I agree with @selipot, I would include both `deploy` and `start` fields in the NetCDF archives.

For the `dirfl` files (if space is limited), having the `start` values instead of the `deploy` might be more useful, e.g. to order the observed data of the floats in chronological order.

**Comment by shaundolk** [comment]
@selipot @philippemiron Agreed. I was operating under the assumption we had to choose between the two start dates, but given the option, including both deploy date and start date would be ideal.

**Comment by selipot** [comment]
@shaundolk @philippemiron it looks like we agree that the next version of the NetCDF files will include `start_[date,lat,lon]` variables and we should get the ragged arrays ordered from that.
